// All app routes as constants — never hardcode route strings in components
export const routes = {
  home:            '/',
  docs:            (slug: string) => `/docs/${slug}`,
  login:           '/login',
  changePassword:  '/change-password',
  resetPassword:   '/reset-password',
  dashboard:       '/dashboard',
  files:           '/files',
  filesTrash:      '/files/trash',
  team:            '/team',
  feedback:        '/feedback',
  reports:         '/reports',
  reportDetail:    (id: string) => `/reports/${id}`,
  calendar:        '/calendar',
  sprints:         '/sprints',
  sprintDetail:    (id: string) => `/sprints/${id}`,
  exams:           '/exams',
  examNew:         '/exams/new',
  examDetail:      (id: string) => `/exams/${id}`,
  examLive:        (id: string) => `/exams/${id}/live`,
  examReview:      (id: string) => `/exams/${id}/review`,
  examAnalytics:   '/exams/analytics',
  examRooms:       '/exam-rooms',
  students:        '/students',
  studentDetail:   (id: string) => `/students/${id}`,
  datasets:        '/admin/datasets',
  datasetDetail:   (id: string) => `/admin/datasets/${id}`,
  settings:        '/settings',
  notifications:   '/notifications',
  monitor:         '/dev/monitor',
  health:          '/api/health',
  healthDetailed:  '/api/health/detailed',
} as const;

// Routes that require authentication (used in middleware)
export const PROTECTED_ROUTES = [
  '/dashboard',
  '/files',
  '/team',
  '/feedback',
  '/reports',
  '/sprints',
  '/exams',
  '/exam-rooms',
  '/students',
  '/admin',
  '/calendar',
  '/settings',
  '/notifications',
  '/dev',
] as const;

// Routes only accessible by admin
export const ADMIN_ONLY_ROUTES = [
  '/files',
  '/files/trash',
  '/team',
  '/admin',
  '/dev/monitor',
] as const;
